from scigym.envs.toy_text.blackjack import BlackjackEnv
from scigym.envs.toy_text.roulette import RouletteEnv
from scigym.envs.toy_text.frozen_lake import FrozenLakeEnv
from scigym.envs.toy_text.nchain import NChainEnv
from scigym.envs.toy_text.hotter_colder import HotterColder
from scigym.envs.toy_text.guessing_game import GuessingGame
from scigym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from scigym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from scigym.envs.toy_text.cliffwalking import CliffWalkingEnv
